### ISSUE TITLE
Add caching support for assets served from the "public/" directory

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#143]
Probably need a way to choose a default value for all assets with the ability to configure caching headers for one-off cases.

For reference:

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
* https://ktor.io/docs/caching.html
* https://nextjs.org/docs/going-to-production#caching

**Comment by kocheick** [comment]
id like to propose an implementation plan for this, and please let me know if you have any feedback:

# Asset Caching Implementation Plan for Kobweb

This document outlines the simplified implementation plan for adding basic configurable asset caching to Kobweb. The focus is on essential caching headers functionality with simple, executable steps.

## Requirements (Essential Scope Only)

1. Configure basic caching headers for assets served from the 'public/' directory
2. Support environment-based defaults (disabled in dev, enabled in prod)
3. Provide simple global configuration with sensible defaults
4. Support basic cache control directives (max-age, no-cache, no-store)

## Implementation Steps

### 1. Extend KobwebConf with Basic Asset Caching Configuration

**Location**: `common/kobweb-common/src/main/kotlin/com/varabyte/kobweb/project/conf/KobwebConf.kt`

Add a simple `assetCaching` section to the `Server` class:

```kotlin
@Serializable
class Server(
    val files: Files,
    val port: Int = 8080,
    val logging: Logging = Logging(),
    val cors: Cors = Cors(),
    val redirects: List<Redirect> = emptyList(),
    val streaming: Streaming = Streaming(),
    val nativeLibraries: List<NativeLibrary> = emptyList(),
    val assetCaching: AssetCaching = AssetCaching(),
) {
    // ... existing code ...

    /**
     * Configuration for basic asset caching.
     * 
     * @property enabled Whether caching is enabled. Defaults to true for PROD and false for DEV.
     * @property maxAge The maximum time assets should be cached before revalidation.
     * @property noCache If true, browsers must revalidate assets with the server before using them.
     */
    @Serializable
    class AssetCaching(
        val enabled: Boolean? = null, // null means use environment default (true for PROD, false for DEV)
        val maxAge: Duration = 24.hours,
        val noCache: Boolean = false,
    )
}
```

### 2. Enhance CachingHeaders Plugin in HTTP.kt

**Location**: `backend/server/src/main/kotlin/com/varabyte/kobweb/server/plugins/HTTP.kt`

Modify the existing CachingHeaders installation to use the new basic configuration:

```kotlin
fun Application.configureHTTP(appProperties: AppProperties, env: ServerEnvironment, conf: KobwebConf) {
    // ... existing code ...

    // Determine if caching should be enabled based on configuration or environment
    val cachingEnabled = conf.server.assetCaching.enabled ?: (env == ServerEnvironment.PROD)
    
    if (cachingEnabled) {
        install(CachingHeaders) {
            options { _, outgoingContent ->
                when {
                    conf.server.assetCaching.noCache -> {
                        CachingOptions(CacheControl.NoCache())
                    }
                    else -> {
                        CachingOptions(
                            CacheControl.MaxAge(
                                maxAgeSeconds = conf.server.assetCaching.maxAge.inWholeSeconds.toInt()
                            )
                        )
                    }
                }
            }
        }
    }
}
```

### 3. Testing and Validation

Create simple tests to verify:

- Caching is disabled in development environment by default
- Caching is enabled in production environment by default
- Configuration overrides work correctly
- Headers are properly set on static assets

## Example Configuration

Here's a simple example configuration:

```yaml
server:
  assetCaching:
    enabled: true
    defaultPolicy:
      maxAge: 7d
      etagEnabled: true
    contentPolicies:
      - contentType: "text/css"
        policy:
          maxAge: 1d
      - contentType: "image/*"
        policy:
          maxAge: 30d
          immutable: true
      - contentType: "application/javascript"
        policy:
          maxAge: 7d
          varyHeaders: ["Accept-Encoding"]
    pathPolicies:
      - pattern: "/public/fonts/*"
        policy:
          maxAge: 365d
          immutable: true
      - pattern: "/public/api-data/*"
        policy:
          maxAge: 5m
          noCache: true
      - pattern: "/public/dynamic/*"
        policy:
          noStore: true
```

## Edge Cases and Considerations

1. **Content Hashing for Static Assets**
   - Implement a content hash system for static assets
   - When files change, their URLs change (e.g., `/styles.123abc.css`)
   - Allow setting very long cache times for hashed resources

2. **Development vs. Production Environments**
   - Keep caching disabled by default in development mode
   - Enable caching by default in production environment
   - Allow overriding these defaults in configuration

3. **CDN Integration**
   - Ensure compatibility with CDN providers like Cloudflare, Fastly, etc.
   - Add support for CDN-specific headers like `CDN-Cache-Control`

4. **Vary Header Support**
   - Add support for the `Vary` header to handle content negotiation
   - Important for responsive images or language-specific content

5. **ETag and Last-Modified Support**
   - Implement ETag generation for assets
   - Add Last-Modified headers based on file modification time
   - Support conditional requests to reduce bandwidth

6. **Cache Busting Mechanism**
   - Provide a simple API to force cache invalidation when needed
   - Could be implemented via query parameters or version path segments

7. **Service Worker Integration**
   - Ensure compatibility with service workers for offline support
   - Consider how caching headers interact with service worker caching

8. **Handling Dynamic Routes**
   - Consider how caching should work with dynamic routes
   - Provide options to control caching for dynamic content

## Testing Plan

1. Test caching headers in development and production environments
2. Test with different content types and path patterns
3. Test static site exports with different hosting platforms
4. Test with CDNs and proxies
5. Test cache busting mechanisms
6. Test with service workers
7. Test conditional requests with ETags
