### ISSUE TITLE
Run Kobweb server in a way that it can be debugged remotely

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#331]
Looking at https://www.jetbrains.com/help/idea/attaching-to-local-process.html I'd need to run the kobweb server with a debug agent attached to it.

This shouldn't be hard to do (the `KobwebStartTask` can do it) but we should allow some configuration, probably in the conf.yaml file?

```yaml
server:
  dev:
    remoteDebugging:
      enabled: true
      port: 5005
```

For an initial release we can set enabled to false, but is there a reason not to just default it to true?
